apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-cd
  namespace: argo
spec:
  project: default
  source:
    repoURL: 'https://github.com/jcholowaty/Poc-Argo.git'
    path: .
    targetRevision: main
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: argo
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
